<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5VFDL3B" failures="1" tests="4" name="Test" time="44.191" errors="0" timestamp="2025-06-15T11:19:29 IST">
  <testcase classname="testcases.login_withddt" name="loginddt" time="6.196"/>
  <testcase classname="testcases.login_withddt" name="loginddt" time="8.393"/>
  <testcase classname="testcases.login_withddt" name="loginddt" time="8.299"/>
  <testcase classname="testcases.login_withddt" name="loginddt" time="0.777">
    <failure type="java.lang.AssertionError" message="OTP logo found for invalid number: 1234567890">
      <![CDATA[java.lang.AssertionError: OTP logo found for invalid number: 1234567890
at testcases.login_withddt.loginddt(login_withddt.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- loginddt -->
</testsuite> <!-- Test -->
